# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
